const CHANGELOG = [
    {
        date: '26/04/2026',
        version: 'v0.10',
        tag: 'ÚLTIMA',
        entries: [
            { type: 'new', text: 'Procurement — nuevo módulo activado en el home y la sidebar para gestionar todas las incidencias de stock. Fase 1: peticiones de compra al departamento de procurement (accesorios faltantes, material de tienda…)' },
            { type: 'new', text: 'Procurement: máquina de estados Pedido → Autorizado OPS → Llegando → Recibido → Cerrado, más Cancelado/Rechazado como vía paralela. Cada estado se marca con un botón propio en el detalle' },
            { type: 'new', text: 'Procurement: cada cambio de estado queda registrado automáticamente con fecha-hora, persona que lo marca y nota opcional. Historial visible al final del panel de detalle' },
            { type: 'new', text: 'Procurement: nueva petición desde botón "+ Nueva petición" — artículo, motivo, pedido por, fecha (auto-hoy editable), BoxID opcional, nº de serie opcional, proveedor opcional' },
            { type: 'new', text: 'Procurement: el botón para el siguiente estado tras "Pedido" se llama "Autorizado OPS" — se marca cuando OPS contesta autorizando la petición por correo' },
            { type: 'new', text: 'Procurement: al pasar a "Llegando" se pide la fecha prevista de llegada; al pasar a "Recibido" se pide la fecha de recepción y queda firmado quién lo recibió' },
            { type: 'new', text: 'Procurement: tabla con filtros por estado (Todos / Pedido / Autorizado OPS / Llegando / Recibido / Cerrado / Cancelado) y búsqueda libre por nombre, BoxID, nº serie, motivo, quien lo pidió o proveedor' },
            { type: 'new', text: 'Procurement: panel de detalle conmutable entre lateral y inferior, con la disposición memorizada por dispositivo (mismo patrón que Garantías). En modo inferior, el panel se redimensiona arrastrando la barrita superior' },
            { type: 'new', text: 'Procurement: aviso visual ámbar cuando una petición lleva ≥ 7 días en estado "Pedido" sin moverse — para no perder el seguimiento' },
            { type: 'new', text: 'Procurement: en el panel de detalle, BoxID y Nº de serie llevan botón de copiar al portapapeles cuando tienen valor — feedback verde al copiar' },
            { type: 'ui', text: 'Procurement: la tabla overview omite BoxID y Nº de serie (se ven en el detalle) — para que la tabla quede legible y sin ruido' },
            { type: 'ui', text: 'Procurement: dropdown de personas compartido con el equipo del módulo Checklist — fuente única, se configura desde allí' },
            { type: 'ui', text: 'Procurement: calendarios en español, lunes-primero, formato DD/MM/AAAA (flatpickr, igual que Garantías)' },
            { type: 'new', text: 'Procurement: sincronización en tiempo real entre dispositivos — los cambios de otra persona aparecen aquí sin refrescar' },
        ]
    },
    {
        date: '23/04/2026',
        version: 'v0.9',
        entries: [
            { type: 'fix', text: 'App: cerrar un modal haciendo clic fuera ya no funciona — solo cierran la X de la esquina, los botones de la propia ventana o ESC. Antes, un drag-select de texto que terminaba sobre el fondo cerraba la ventana de golpe y se perdía lo escrito' },
            { type: 'ui', text: 'Garantías · Defectuoso del cliente: el campo "Tienda destino" pasa a llamarse "Tienda destino RTO". Tooltip al pasar el ratón aclara que es solo para casos de RTO a franquicia' },
            { type: 'fix', text: 'Checklist: saltar una tarea ahora cuenta como "procesarla" para la alerta roja. Si una tarea con umbral crítico de 1 día se saltó ayer, hoy no salta en rojo — queda solo con el chip "hace N días" en gris. El rojo se reserva para tareas que llevan más del umbral sin hacer NI saltar' },
            { type: 'ui', text: 'App: logo y favicon actualizados con fondo transparente. El blend que escondía el fondo blanco se mantiene como seguro — es inocuo con PNGs ya transparentes y cubre cualquier tinte residual que pudiera quedar' },
        ]
    },
    {
        date: '22/04/2026',
        version: 'v0.8',
        entries: [
            { type: 'ui', text: 'Checklist · Tareas persistentes: la cabecera de la columna reordenada — título a la izquierda, contador y botón Archivo agrupados a la derecha' },
            { type: 'ui', text: 'Checklist · Tareas persistentes: el contador vuelve al formato X / Y, ahora como progreso del día (archivadas hoy / total del día). Empieza en 0/N y sube mientras completas' },
            { type: 'new', text: 'Checklist · Tareas persistentes: marcar como hecha MUEVE la tarea al archivo en lugar de dejarla en la lista. La lista de vigentes queda siempre limpia. La tarea se guarda en el archivo con TODO su contenido (nombre, prioridad, nota) y se puede recuperar de vuelta a vigentes con un clic' },
            { type: 'new', text: 'Checklist · Tareas persistentes: pequeño briefing "Recién archivadas" al pie de la lista de vigentes con las 3 últimas completadas (hora · tarea · quién). Clic → abre el archivo completo' },
            { type: 'new', text: 'Checklist · Tareas persistentes: botón "Archivo" en la cabecera de la columna abre el modal con todas las tareas archivadas, agrupadas por fecha. Cada entrada tiene botones de Recuperar (↺) y Eliminar (✕). Botón "Limpiar" con contraseña en la cabecera del modal para vaciar todo de golpe' },
            { type: 'fix', text: 'Checklist · Tareas persistentes: borrar una tarea ya no deja rastro en el archivo. Solo las que completas explícitamente aparecen archivadas' },
            { type: 'fix', text: 'Checklist: sincronización en tiempo real del módulo entre dispositivos (onSnapshot de Firestore). Cualquier cambio hecho en otro PC aparece sin refrescar, y las notas de las tareas persistentes ya no pueden ser pisadas por una pestaña con datos viejos' },
            { type: 'new', text: 'Xfer Reg · Resumen: segundo botón en la fila "Printed cover" que copia BoxID + Nombre + Categoría separados por tabs, listo para pegar en las columnas B/C/D de la plantilla de petición de carátulas' },
            { type: 'ui', text: 'Xfer Reg · Resumen: tabla con encabezados de columna (Estado / Uds / Unit price / % / IDs / Carátulas). Panel más estrecho, tabla centrada en lugar de estirada, y botones de copia con más aire' },
            { type: 'fix', text: 'Checklist · Histórico: se duplicaban entradas de días pasados (mezcla de versiones antiguas que auto-escribían en cada marca + archivo al "Iniciar {fecha}"). Ahora se deduplican al cargar y al archivar se hace upsert, no append' },
            { type: 'new', text: 'Checklist · Histórico: botón temporal "Limpiar" en la cabecera del modal — borra todo el histórico de la tienda tras pedir contraseña, por si alguien tenía datos ya corruptos' },
            { type: 'new', text: 'App: favicon personalizado — capibara para el home, y cada módulo tiene su icono con su color (Checklist morado, Garantías ámbar, Xfer Reg azul, Ajustes indigo). Al ver pestañas abiertas a la vez, sabes de qué va cada una de un vistazo' },
            { type: 'new', text: 'Checklist · Tareas persistentes: cada tarea puede llevar una nota libre — consejos, pasos, contexto. Abierta desde la píldora "Notas" en la fila. Modal con textarea + botón "Firmar" que inserta tu nombre y la fecha al final de tu aportación' },
            { type: 'new', text: 'Checklist · Tareas persistentes: doble clic en el nombre para renombrar una tarea inline (Enter guarda, Escape cancela)' },
            { type: 'ui', text: 'Checklist · Tareas persistentes: la palabra "Prioridad" se retira de la fila; aparece como tooltip al pasar el ratón por el rollup. Su sitio lo ocupa la píldora "Notas" (azul llena si la tarea tiene contenido, outline tenue si no)' },
            { type: 'ui', text: 'App: escala global más compacta — root a 15 px (antes 16 px), paddings/tarjetas del home y logo reducidos. Todo el resto de la app escala con los rem' },
            { type: 'ui', text: 'Checklist: tipografía y padding de los bloques de tarea reducidos ~25 % para un aire más minimalista' },
            { type: 'ui', text: 'Checklist: el chip "hace N días" se achica y pasa a apilarse bajo la hora — las filas ya no se estiran por la píldora' },
            { type: 'ui', text: 'Checklist · Tareas persistentes: misma pasada de reducción (card, header, nombre, "hecho por", rollup de prioridad, botón X)' },
            { type: 'ui', text: 'Checklist: el chip "hace N días" solo aparece si la tarea tiene criticidad configurada Y lleva más de 1 día sin procesarse. Antes salía en todas las tareas — ruido innecesario en las cotidianas' },
            { type: 'fix', text: 'Checklist: tras cruzar medianoche, las tareas hechas el día anterior ya no se volvían visualmente "hace 1 día" ni "críticas" hasta que pulsabas "Iniciar {fecha}". El marco temporal ahora es el propio ciclo de la checklist (cycleDate), no el reloj de pared' },
            { type: 'fix', text: 'Checklist: las tareas ya hechas o saltadas nunca se pintan como críticas (antes el rojo del "crítica" podía tapar el verde de "hecha" cuando tenían umbral bajo)' },
            { type: 'fix', text: 'Checklist · Criticidad: "N días sin hacerla antes de crítica" ahora funciona como suena — la alerta roja salta solo tras más de N días sin marcarla. Una tarea diaria (umbral 1) ya no se pinta roja a la mañana siguiente de completarla' },
            { type: 'ui', text: 'Checklist: fuera del ciclo de hoy (cuando aún no has pulsado "Iniciar {fecha}"), el tinte amarillo/naranja/rojo por hora vencida se desactiva — era ruido porque toda la lista quedaba en rojo' },
        ]
    },
    {
        date: '21/04/2026',
        version: 'v0.7',
        entries: [
            { type: 'fix', text: 'Checklist (modo Editar): en monitor estrecho los botones de la barra ya no se salen por la derecha hacia la columna de Tareas persistentes — ahora envuelven a segunda fila dentro de la columna' },
            { type: 'ui', text: 'Checklist: el botón "Iniciar nuevo día" se simplifica — ahora es un único botón con la fecha incorporada ("Iniciar miércoles, 22 de abril"), sin etiqueta separada debajo' },
            { type: 'ui', text: 'Checklist: dentro del modo Editar se ocultan los botones "Histórico" e "Iniciar {fecha}" — no pintan nada mientras configuras la lista' },
            { type: 'new', text: 'Checklist · Tareas persistentes: campo Prioridad debajo del desplegable. Rollup 001–100 (más alto = más prioritario). Colores graduales, de rosa pálido a rojo intenso según la prioridad, tanto en el select cerrado como en la lista desplegable. La lista se reordena sola; completadas al final' },
            { type: 'new', text: 'Checklist: columna derecha = Tareas persistentes. Se van añadiendo tareas que surgen durante el día, se marcan con su "hecho por" y no se reinician. Pensadas para recordar cosas sueltas del día a día' },
            { type: 'ui', text: 'Checklist: layout 50/50 — izquierda checklists diarias, derecha Tareas persistentes' },
            { type: 'ui', text: 'Checklist: cada día se inicia manualmente con el botón "Iniciar {fecha}". Al hacerlo, el contenido del día anterior se archiva al histórico (incluidas las tareas que se quedaron sin marcar)' },
            { type: 'new', text: 'Checklist · Histórico: entradas "sin marcar" en gris cuando una tarea diaria no se procesó antes de archivar el día' },
            { type: 'new', text: 'Checklist (modo Editar): botón "+" a la derecha de cada tarea → "Añadir tarea siguiente". Hereda la hora de la tarea origen y se coloca justo a continuación, sin tocar el resto del orden' },
            { type: 'ui', text: 'Checklist: modo "Editar" completo — añade, modifica, elimina y reordena tareas (drag-and-drop). Fuera del modo la interfaz queda limpia, centrada solo en marcar quién hizo cada tarea' },
            { type: 'new', text: 'Checklist: cada tarea puede llevar un enlace (URL + nombre visible). Clic en el chip violeta y abre en pestaña nueva. Si no pones nombre, el enlace hace de nombre' },
            { type: 'new', text: 'Checklist: opción "⏭ Saltar" en el desplegable — para tareas que no tocan hoy (p. ej. el formulario de festivos en días de diario). Cuenta como procesada' },
            { type: 'new', text: 'Checklist: cada tarea recuerda cuándo se marcó como hecha por última vez — un chip junto al nombre indica "hace N días"' },
            { type: 'new', text: 'Checklist: en el modo Editar puedes asignar un umbral "días sin hacerla antes de crítica". Al superarlo, la tarea se pinta en rojo con aviso' },
            { type: 'ui', text: 'Checklist: en modo uso, las tareas hechas o saltadas bajan automáticamente al final, quedando arriba las pendientes. En modo Editar el orden real se mantiene para poder arrastrar. Separador fino entre ambos bloques. Hechas en verde, saltadas en gris' },
            { type: 'new', text: 'Checklist: histórico de los últimos 14 días por checklist. Botón "Histórico" en la barra abre un modal con el detalle día a día — quién hizo cada tarea, si se saltó o quedó sin marcar. Filtro por tarea concreta (incluye tareas ya eliminadas que sigan en el log)' },
            { type: 'new', text: 'Checklist (modo Editar): botón "Ordenar por hora" que reordena la lista ascendentemente y reactiva la inserción automática por hora para las nuevas tareas' },
            { type: 'fix', text: 'Checklist: al ordenar por hora, las tareas con la misma hora conservan el orden que tenían; ya no se reordenan alfabéticamente' },
            { type: 'new', text: 'Checklist: tinte automático cuando se pasa la hora de una tarea pendiente — amarillo al instante, naranja a los 30 min, rojo tenue a la hora. Se actualiza sin recargar' },
            { type: 'ui', text: 'Checklist: el orden manual se guarda y se respeta; las nuevas tareas siguen insertándose por hora hasta que reordenas (entonces se añaden al final)' },
            { type: 'new', text: 'Checklist: varias listas con nombre (Apertura, Cierre, Limpieza…). Se cambia de checklist con el selector de arriba. Botones para crear nueva, renombrar la actual o eliminarla' },
            { type: 'new', text: 'Checklist: configura el equipo de la tienda (botón "Equipo") — nombres de los miembros que marcarán las tareas. El "hecho por" es un desplegable con esos nombres' },
            { type: 'fix', text: 'Checklist: el selector de hora ahora fuerza formato 24h (flatpickr con locale español), independiente del SO' },
            { type: 'new', text: 'Checklist — nuevo módulo para las tareas de apertura/cierre/limpieza de la tienda. Añade, edita o elimina tareas con hora aproximada (24h) y nombre libre. Lista ordenada automáticamente por hora ascendente; persistencia por tienda en Firestore' },
            { type: 'ui', text: 'Home: sin título repetido "Dashboard" en el cuerpo. Tarjetas de cada módulo como rectángulos compactos de ancho fijo, centrados, en 3 columnas. Logo de CapiTool completo y visible encima, con versión de fondo al 15 % de opacidad' },
            { type: 'fix', text: 'Control de ajustes · Resumen: el "Margen" pasa a ser por Quarter (se reinicia cada Q) y se renombra a "Margen Q €". Movido junto al grupo Q en el orden de columnas' },
            { type: 'ui', text: 'Control de ajustes · Resumen: cifras de € (Ajustes, Neto, Neto acum Q, Neto acum año) ya no llevan color. Solo los % se pintan en rojo cuando se salen del rango (−0,40 % a +0,10 %)' },
            { type: 'fix', text: 'Control de ajustes: análisis basado en "Adj Sale Val" en lugar de "Adj Cost Val" — resumen, stats, filtros de € y resaltado de columna en el listado' },
            { type: 'ui', text: 'Control de ajustes: rango tolerable (antes "rango aceptable"), aplicado tanto a ajustes anuales como trimestrales' },
            { type: 'fix', text: 'Control de ajustes: al desmarcar una fila filtrada, el cambio no siempre se guardaba de verdad en Firestore. Ahora sí — también arregla el borrar ventas de una semana' },
            { type: 'new', text: 'Control de ajustes — vistas separadas: pestañas "Resumen semanal" y "Listado completo". Los filtros viven con el listado; cada navegador recuerda en qué vista te quedaste' },
            { type: 'new', text: 'Control de ajustes · Resumen: tres columnas nuevas anuales — Neto acum año, Ventas acum año y % año (cuentan desde el inicio de WK1 del año, no desde el 1 de enero)' },
            { type: 'new', text: 'Control de ajustes · Resumen: columna "Margen €" — cuántos € de ajustes te quedan antes de salir del rango aceptable. Negativo y rojo = ya estás fuera' },
            { type: 'ui', text: 'Control de ajustes · Resumen: regla del rango aceptable visible en la cabecera — −0,40 % a +0,10 % sobre ventas anuales. Cualquier % anual fuera del rango se pinta rojo' },
            { type: 'ui', text: 'Control de ajustes · Resumen: columnas anuales agrupadas con un fondo lavanda y separación visual del bloque trimestral' },
            { type: 'new', text: 'Control de ajustes — Resumen por semana con los cálculos que antes hacías a mano en tu hoja de cálculo' },
            { type: 'new', text: 'Control de ajustes: semanas según el calendario de la compañía (sábado a viernes) — WK17 2026 = 18–24 abril, etc.' },
            { type: 'new', text: 'Control de ajustes · Resumen: columnas Q, Semana, Rango, Ajustes, Filtrados, Neto, Neto acum Q, Ventas WK, Ventas acum Q, % WK, % acum Q' },
            { type: 'new', text: 'Control de ajustes · Resumen: introduce las ventas de cada semana haciendo clic directamente en la celda — se persisten en Firestore por tienda' },
            { type: 'new', text: 'Control de ajustes · Resumen: aviso en banner ámbar listando las semanas que aún no tienen ventas introducidas' },
            { type: 'ui', text: 'Control de ajustes · Resumen: porcentajes coloreados por umbral — < 1 % verde, 1–3 % ámbar, ≥ 3 % rojo (sobre el valor absoluto)' },
            { type: 'ui', text: 'Control de ajustes · Resumen: filas separadoras por Quarter para ver de un vistazo el inicio de cada ciclo' },
        ]
    },
    {
        date: '20/04/2026',
        version: 'v0.6',
        entries: [
            { type: 'ui', text: 'App: la aplicación se llama ahora CapiTool (antes OmniTool)' },
            { type: 'new', text: 'Control de ajustes — nuevo módulo para analizar ajustes de inventario semana a semana' },
            { type: 'new', text: 'Control de ajustes: sube el CSV del Adjustment Report; cada nueva subida añade líneas y deduplica las ya conocidas, conservando los flags de "Filtrar"' },
            { type: 'new', text: 'Control de ajustes: tabla con las 18 columnas del reporte + columna "Filtrar" — marca cualquier ajuste para excluirlo del análisis (p. ej. cambios de grado asumidos, reposiciones legítimas)' },
            { type: 'new', text: 'Control de ajustes: filtros por semana, mes, categoría, type, rango de € y búsqueda por Box Name / Box ID / Notas / Order Nº' },
            { type: 'new', text: 'Control de ajustes: vista alternativa "Solo filtrados" / "Sin filtrar" para revisar lo excluido o lo que penaliza, por separado' },
            { type: 'new', text: 'Control de ajustes: cabecera con el rango de fechas cubierto y contador total — sabes hasta dónde está actualizado de un vistazo' },
            { type: 'fix', text: 'Xfer Reg · Comprobador: las líneas justificadas como "Ya enviado (RMA…)" / "Vendido en tienda" / etc. ya no consumen el match XFER. Antes podían robarle el emparejamiento a una línea idéntica realmente enviada, dejándola como pendiente por error' },
        ]
    },
    {
        date: '17/04/2026',
        version: 'v0.5',
        entries: [
            { type: 'new', text: 'Garantías — nuevo módulo para llevar el control de cada cobertura' },
            { type: 'new', text: 'Estados: Pedido → Recibido → Entregado → Cerrado, con Fallido como vía paralela' },
            { type: 'new', text: 'Filtros por estado con conteos en vivo + búsqueda por UMID, Box ID o Box Name' },
            { type: 'new', text: 'Tabla ordenable por cualquier columna (especial atención a fechas)' },
            { type: 'new', text: 'Aviso visual: las garantías en estado Pedido con ≥ 7 días se resaltan en ámbar' },
            { type: 'new', text: 'Panel lateral con acciones por estado (recibir, entregar, procesar RMA/RTO)' },
            { type: 'new', text: 'Registro de llamadas al cliente con fecha/hora editable y resultado de contacto' },
            { type: 'new', text: 'Garantías fallidas: botón "Generar nuevo intento" que enlaza con la original' },
            { type: 'new', text: 'Tienda origen como dropdown con las 69 tiendas para futuras estadísticas' },
            { type: 'ui', text: 'Botón Garantías colocado a la derecha de Xfer Reg en home y sidebar' },
            { type: 'ui', text: 'Tabla optimizada para monitor vertical: UMID y Box ID son iconos de copiar al portapapeles' },
            { type: 'new', text: 'Sección Defectuoso ampliada: descripción del defecto, fecha de venta, tipo (RMA Externa/Interna o RTO), tienda destino, investigado por' },
            { type: 'ui', text: 'Acción "Cerrar caso" sustituye a "Procesar defectuoso", con fecha y responsable de cierre' },
            { type: 'new', text: 'Inspector de garantía con dos disposiciones: lateral (monitor horizontal) o inferior (monitor vertical), recordada por navegador' },
            { type: 'new', text: 'Panel inferior redimensionable: arrastra el borde superior para ajustar el alto (también se recuerda por ordenador)' },
            { type: 'ui', text: 'Panel inferior en modo tarjetas: secciones distribuidas en columnas para aprovechar el ancho y reducir scroll' },
            { type: 'ui', text: 'Formato de fechas unificado en DD/MM/AAAA y hora en 24h en toda la aplicación' },
            { type: 'new', text: 'Calendarios en lunes-primero y formato 24h en Garantías (flatpickr con locale español, independiente del SO)' },
            { type: 'fix', text: 'Panel inferior: la tarjeta en edición se expande al ancho completo y los inputs se adaptan sin desbordar' },
            { type: 'ui', text: 'Al editar una tarjeta, ésta sube al top del panel para que el formulario quede siempre a la vista' },
            { type: 'ui', text: 'Iconos de comentarios y llamadas unificados en SVG line-icon minimalista (ya no emojis)' },
            { type: 'new', text: 'Botones de copiar UMID / Box ID se resaltan en rojo si falta uno de los dos en la línea' },
            { type: 'new', text: 'Sincronización entre dispositivos: los cambios de otros usuarios de la misma tienda se traen al volver a la pestaña, al abrir una garantía, o con el botón manual de refrescar' },
            { type: 'new', text: 'Detección de conflictos al guardar: si otro navegador modificó la misma garantía mientras la estabas editando, saltan opciones para sobrescribir o descartar tus cambios' },
            { type: 'ui', text: 'Tabla responsive: columnas se ocultan progresivamente en pantallas estrechas (Por, Test Order, Entregado, Recibido, y finalmente los iconos de copiar UMID/Box ID) — Tienda origen se mantiene el máximo posible' },
            { type: 'new', text: 'Vista móvil: cada garantía se muestra como tarjeta de 3 líneas — Estado + Nombre + iconos arriba, Tienda origen en medio, y las tres fechas (Ped/Rec/Ent) etiquetadas abajo' },
            { type: 'ui', text: 'Cerrado es ahora una categoría aparte: "Todos" muestra sólo casos activos, y los fallidos cuyo reintento acabó en Cerrado se agrupan con su caso cerrado' },
            { type: 'ui', text: 'Chip "Cerrado" separado visualmente: movido al final con un separador, icono de archivador delante para reforzar que es el histórico' },
            { type: 'ui', text: 'Nombre del producto (Box Name) ahora puede ir en varias líneas si es largo, sin forzar scroll horizontal' },
            { type: 'ui', text: 'Barra de filtros/búsqueda se adapta: búsqueda se expande y los botones bajan a una segunda fila en monitores verticales' },
        ]
    },
    {
        date: '14/04/2026',
        version: 'v0.4',
        entries: [
            { type: 'new', text: 'Backup local: descarga y restaura el estado completo como JSON' },
            { type: 'new', text: 'Revisión: % de coste en todas las tablas (tipo incorrecto, justificados, pendientes)' },
            { type: 'new', text: 'Revisión: envíos no solicitados agrupados por tipo, RMA Stock Out expandible' },
            { type: 'ui', text: 'Revisión: "Enviado XFER" ahora muestra % por coste descontando justificados' },
            { type: 'new', text: 'Imprimir "Buscando no encontrado" desde Resumen y Revisión (con categoría y %)' },
            { type: 'new', text: 'Ordenar: tercer modo "Estado" — agrupa por estado, colapsado, expandible' },
            { type: 'fix', text: 'Keys de estado estables — los estados ya no bailan al cambiar de vista' },
            { type: 'fix', text: 'Migración automática de estados guardados al nuevo formato de keys' },
            { type: 'ui', text: 'Vista Estado: tiendas ordenadas por peso (mayor coste primero)' },
            { type: 'ui', text: 'Impresión en vista Estado: solo el grupo desplegado, con cabecera' },
            { type: 'fix', text: 'Grupos de estado ya no se colapsan solos (snapshot Firestore controlado)' },
            { type: 'new', text: 'Archivo semanal: archivar xfer con nombre editable (ej: "Xfer Reg WK15 2026")' },
            { type: 'new', text: 'Panel de Archivo: recuperar o eliminar xfers archivados con resumen de stats' },
            { type: 'ui', text: 'Botón Ordenar: switch horizontal de 3 posiciones, nombre dinámico' },
            { type: 'ui', text: 'Botones Archivar/Archivo apilados en azul junto a la botonera principal' },
            { type: 'ui', text: 'Eliminar archivo protegido: doble confirmación + contraseña de tienda' },
        ]
    },
    {
        date: '11/04/2026',
        version: 'v0.3',
        entries: [
            { type: 'ui', text: 'Dropbox y barra de progreso integrados en un único marco' },
            { type: 'ui', text: 'Dropbox se transforma al cargar archivo (Clark Kent / Superman)' },
            { type: 'ui', text: 'Botones renombrados: Resumen, Revisión, Imprimir, Ordenar' },
            { type: 'new', text: 'Botón Ordenar: alterna entre vista por Secciones (C/H/S) y por Tiendas' },
            { type: 'new', text: 'Tooltips de ayuda en botones Resumen y Revisión (hover sobre ?)' },
            { type: 'new', text: 'Enlace a Looker Studio en tooltip de Revisión' },
            { type: 'ui', text: 'Columna Unit Cost oculta (pantalla e impresión)' },
            { type: 'ui', text: 'Botones con tamaño uniforme, layout responsive con wrap' },
            { type: 'ui', text: 'Header sticky: barra de progreso y botones fijos al hacer scroll' },
            { type: 'fix', text: 'Reducido padding superior del contenido' },
            { type: 'ui', text: 'Home: módulos deshabilitados muestran solo "Próximamente" como subtítulo' },
            { type: 'fix', text: 'Estado de línea puede revertirse a vacío (—)' },
            { type: 'new', text: 'Resumen: botón para copiar BoxIDs por estado de descuento' },
            { type: 'fix', text: 'Tooltip de Revisión: enlace a Looker Studio clicable (pin con click)' },
        ]
    },
    {
        date: '10/04/2026',
        version: 'v0.2',
        entries: [
            { type: 'ui', text: 'Título del módulo activo centrado en la barra superior' },
            { type: 'new', text: 'Barra de progreso de fulfilment en el header del módulo Xfer Reg — se actualiza en tiempo real' },
            { type: 'ui', text: 'Header reestructurado: dropbox e info a la izquierda, progreso en el centro, botones a la derecha' },
            { type: 'ui', text: 'Botones Análisis y Comprobador del mismo tamaño' },
            { type: 'new', text: 'Xfer Reg — Comprobador de envíos: cruza Stock Transfers con Xfer Reg' },
            { type: 'new', text: 'Comprobador — % real de envíos XFER Regular Transfer Out' },
            { type: 'new', text: 'Comprobador — detecta envíos con tipo incorrecto (S/R, RMA, etc.)' },
            { type: 'new', text: 'Comprobador — items justificados por estado (Printed cover, Vendido, etc.)' },
            { type: 'new', text: 'Comprobador — items pendientes con detección de sustitutos similares' },
            { type: 'new', text: 'Comprobador — envíos no solicitados (artículos extra)' },
            { type: 'new', text: 'Comprobador — manejo de encoding mojibake en nombres de tienda' },
            { type: 'new', text: 'Xfer Reg — panel de Resumen con desglose por estado, valor efectivo, barra de progreso y alertas' },
            { type: 'new', text: 'Xfer Reg — el resumen se actualiza en tiempo real al cambiar estados' },
            { type: 'new', text: 'Botón de resumen en el sidebar (icono de barras)' },
            { type: 'new', text: 'Lista cerrada de 69 tiendas — selector dropdown, sin texto libre' },
            { type: 'new', text: 'Contraseña por tienda — se establece en el primer acceso y se pide en los siguientes' },
            { type: 'new', text: 'Panel de administrador — ver todas las tiendas registradas, contraseñas, último acceso y borrar datos' },
            { type: 'new', text: 'Doble confirmación en Limpiar — evita borrados accidentales' },
            { type: 'ui', text: 'Dropbox y barra de archivo integrados en el header del módulo' },
            { type: 'new', text: 'Sincronización en la nube — los datos se guardan en Firebase Firestore, accesibles desde cualquier dispositivo' },
            { type: 'new', text: 'Selector de tienda al abrir la app — cada tienda tiene sus propios datos aislados' },
            { type: 'new', text: 'Panel de configuración (engranaje en sidebar): muestra tienda activa, cambiar tienda y restablecer datos' },
            { type: 'new', text: 'Restablecimiento de fábrica con doble confirmación — borra todos los datos de la tienda en la nube' },
            { type: 'new', text: 'Sincronización en tiempo real — los cambios de estado se reflejan al instante en todos los dispositivos conectados' },
            { type: 'new', text: 'Xfer Reg — diseño responsive: la tabla se escala automáticamente en ventanas estrechas' },
            { type: 'fix', text: 'Xfer Reg — botones de salto C (Críticos) ahora funcionan correctamente' },
            { type: 'new', text: 'Xfer Reg — tooltip en botones de salto: muestra nº items, % total y listado de Box Name + % al hacer hover' },
            { type: 'new', text: 'Xfer Reg — tooltip se posiciona arriba automáticamente si no cabe abajo' },
            { type: 'ui', text: 'Botón Novedades reubicado junto al título OmniTool' },
            { type: 'ui', text: 'Texto de formato esperado actualizado en la zona de upload' },
        ]
    },
    {
        date: '09/04/2026',
        version: 'v0.1',
        entries: [
            { type: 'new', text: 'Dashboard con 6 módulos: Xfer Reg, Procurement, Garantías, Abandoned 45 días, Checklist, Entrenamientos' },
            { type: 'new', text: 'Topbar fija + sidebar con iconos y navegación' },
            { type: 'new', text: 'Módulos no implementados marcados con badge "Próximamente" y estado disabled' },
            { type: 'new', text: 'Xfer Reg — upload de CSV con drag & drop' },
            { type: 'new', text: 'Xfer Reg — tabla con 3 bloques: Críticos (>0.5%), +Hardware, Software' },
            { type: 'new', text: 'Xfer Reg — items expandidos por quantity, ordenados por coste descendente' },
            { type: 'new', text: 'Xfer Reg — tiendas ordenadas por % de fulfilment descendente dentro de cada bloque' },
            { type: 'new', text: 'Xfer Reg — columna Estado con selector coloreado (Enviado, Vendido en tienda, Ya enviado, Printed cover, Buscando no encontrado, No shipeable, REVISAR)' },
            { type: 'new', text: 'Xfer Reg — columna % con colores por tier: 2%+ rojo, 1%+ naranja, 0.5%+ amarillo' },
            { type: 'new', text: 'Xfer Reg — % de fulfilment por tienda y por sección' },
            { type: 'new', text: 'Xfer Reg — botones de salto entre secciones (C/H/S) con flash de 5s al aterrizar' },
            { type: 'new', text: 'Xfer Reg — formato imprimible: landscape, B&W, compacto, cada tienda enmarcada, secciones en hojas separadas, columna Notas y checkbox solo en print' },
            { type: 'new', text: 'Panel de Novedades (changelog) accesible desde la topbar' },
        ]
    }
];
