const STORES = [
    'A Coruña Juan Florez',
    'A Coruña Marineda City',
    'Albacete Concepción',
    'Alcalá Magna',
    'Alcorcón TresAguas',
    'Algeciras Puerta Europa',
    'Alicante Alfonso X El Sabio',
    'Alicante Gran Vía',
    'Almería Torrecárdenas',
    'Barcelona Fabra i Puig',
    'Barcelona Gran de Gràcia',
    'Barcelona La Maquinista',
    'Barcelona Passeig Sant Joan',
    'Barcelona Sant Antoni',
    'Barcelona Sants',
    'Bilbao Areilza',
    'Bilbao Ballonti',
    'Bilbao de la Cruz',
    'Castellón Colón',
    'Ciudad Real Ramón y Cajal',
    'Córdoba Cruz Conde',
    'Elche Glorieta',
    'Getafe Madrid',
    'Gijón Uría',
    'Girona Espai',
    'Granada San Antón',
    'Hospitalet Just Oliveras',
    'Huelva Berdigón',
    'Jerez Santa María',
    'Leganés Juan Muñoz',
    'León Espacio',
    'León Ordoño',
    'Lleida Blondel',
    'Logroño Gran Vía',
    'Madrid Alcalá',
    'Madrid Atocha',
    'Madrid Bravo Murillo',
    'Madrid Hortaleza',
    'Madrid Islazul',
    'Madrid La Laguna',
    'Madrid La Vaguada',
    'Madrid Las Rosas',
    'Madrid Usera',
    'Málaga de la Mota',
    'Málaga Rosaleda',
    'Móstoles Plaza Pradillo',
    'Murcia Primo de Rivera',
    'Palma Carrer d\'Aragò',
    'Palma FAN Mallorca Shopping',
    'Palma Joan March',
    'Salamanca Mirat',
    'San Sebastián - Plaza Cataluña',
    'Santa Coloma de Gramenet',
    'Santander San Fernando',
    'Sevilla Asunción',
    'Sevilla Imagen',
    'Sevilla Nervión',
    'Sevilla Santa Justa',
    'Talavera Trinidad',
    'Terrassa Fontvella',
    'Torrent Avinguda',
    'Valencia Benimaclet',
    'Valencia Fernando',
    'Valencia Ruzafa',
    'Valladolid Teresa Gil',
    'Vigo Camelias',
    'Vilanova Macià',
    'Vitoria Independencia',
    'Zaragoza Carmen'
];

// Admin password — change this to whatever you want
const ADMIN_PASSWORD = 'omni2026';
